- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
  #  - !type:RoleTimeRequirement #DeltaV
  #    role: JobCargoTechnician
  #    time: 21600 #6 hrs
    #- !type:RoleTimeRequirement   #Parkstation - No longer has these requirements from here.
    #  role: JobSalvageSpecialist
    #  time: 10800 #3 hrs
    #- !type:RoleTimeRequirement # DeltaV - Courier role time requirement
    #  role: JobMailCarrier
    #  time: 7200 # 2 hours
    #- !type:DepartmentTimeRequirement
    #  department: Logistics # DeltaV - Logistics Department replacing Cargo
    #  time: 43200 #DeltaV 12 hours
    #- !type:OverallPlaytimeRequirement
    #  time: 144000 #40 hrs     # Parkstation - No longer has these requirements till here.
  # weight: 10   # Parkstation - No longer command.
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  #- Salvage # Parkstation - Salvage is now engineering
  - Mail # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  - Quartermaster
  - Maintenance
  #- Command # Parkstation - Quartermaster isnt a head anymore.
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml
  - External # DeltaV - for promoting salvage specialists
  #special: # Parkstation - No longer command.
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ]
  #- !type:AddComponentSpecial
  #  components:
  #    - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatBeretLogi
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetService #ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelQuartermasterFilled
  duffelbag: ClothingBackpackDuffelQuartermasterFilled
