- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  antagAdvantage: 3 # DeltaV - Reduced TC: External Access + Free hardsuit and weapons
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering # DeltaV - Logistics Department replacing Cargo # ParkStation - Engineering is now their home.
      time: 21600 #DeltaV 6 hrs
  #  - !type:OverallPlaytimeRequirement #DeltaV
  #    time: 36000 #10 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-ce # Parkstation - CE is now the head instead of QM
  access:
  - Engineering # ParkStation-EngineeringSalvagers
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
